la-mia-pizzeria-static/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        [Key] public int Id { get; set; }

        [Required(ErrorMessage = "Il campo Nome è obbligatorio.")]
        [MinLength(3, ErrorMessage = "Il campo Nome deve avere almeno 3 caratteri.")]
        [MaxLength(50, ErrorMessage = "Il campo Nome non può superare i 50 caratteri.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Il campo Descrizione è obbligatorio.")]
        [MaxLength(250, ErrorMessage = "Il campo Descrizione non può superare i 250 caratteri.")]
        [MinWords(5)]
        public string Description { get; set; }

        [Required(ErrorMessage = "Il campo Prezzo è obbligatorio.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Il campo Prezzo deve essere maggiore di zero")]
        public decimal Price { get; set; }

        public string? ImagePath { get; set; }

        public int? CategoryId { get; set; }
        public Category? Category { get; set; }

        public List<Ingredient>? Ingredients { get; set; }

        public Pizza() { }
        public Pizza(string nome, string descrizione, string foto, decimal prezzo, int categoriaId) : this()
        {
            Name = nome;
            Description = descrizione;
            ImagePath = foto;
            Price = prezzo;
            CategoryId = categoriaId;
        }
    }
}

la-mia-pizzeria-static/Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using la_mia_pizzeria_static.Data;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;

namespace LaMiaPizzeria.Controllers
{
    [Authorize]
    public class PizzaController : Controller
    {
        private readonly ILogger<PizzaController> _logger;

        public PizzaController(ILogger<PizzaController> logger)
        {
            _logger = logger;
        }

        
        public IActionResult Index()
        {
            return View("Index");
        }

        [HttpGet]
        [Authorize(Roles = "USER,ADMIN")]
        public IActionResult GetAllPizzas()
        {
            return View(PizzaManager.GetAllPizzas());
        }

        [HttpGet]
        [Authorize(Roles = "USER,ADMIN")]
        public IActionResult GetPizza(int id)
        {
            try
            {
                var pizza = PizzaManager.GetPizza(id);
                if (pizza != null)
                    return View(pizza);
                else
                    //return NotFound();
                    return View("Errore", new ErrorViewModel($"La pizza {id} non è stata trovata!"));
            }
            catch (Exception e)
            {
                return View("Errore", new ErrorViewModel(e.Message));
                //return BadRequest(e.Message);
            }
        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult CreatePizza() // Restituisce la form per la creazione di pizze
        {
            
            List<Category> categories = PizzaManager.GetAllCategories();
            PizzaFormModel model = new PizzaFormModel( categories);
            model.CreateIngredients();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult CreatePizza(PizzaFormModel pizzaDaInserire)
        {
            if (ModelState.IsValid == false)
            {
                // Ritorno la form di prima con i dati della pizza
                // precompilati dall'utente
                pizzaDaInserire.Categories = PizzaManager.GetAllCategories();
                pizzaDaInserire.CreateIngredients();
                return View("CreatePizza", pizzaDaInserire);
            }

            PizzaManager.InsertPizza(pizzaDaInserire.Pizza, pizzaDaInserire.SelectedIngredients);
            // Richiamiamo la action Index affinché vengano mostrate tutte le pizze
            // inclusa quella nuova
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        // Mi serve l'ID della pizza per:
        // 1) Indicare alla view QUALE pizza devo modificare
        // 2) Popolare la form della view coi dati della pizza che sto per modificare
        public IActionResult UpdatePizza(int id) // Restituisce la form per l'update di una pizza
        {
            var pizza = PizzaManager.GetPizza(id);
            if (pizza == null)
                return NotFound();
            PizzaFormModel model = new PizzaFormModel(pizza, PizzaManager.GetAllCategories());
            model.CreateIngredients();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult UpdatePizza(int id, PizzaFormModel pizzaDaModificare) // Restituisce la form per la creazione di pizze
        {
            if (ModelState.IsValid == false)
            {
                // Ritorno la form di prima con i dati della pizza
                // precompilati dall'utente
                pizzaDaModificare.Categories = PizzaManager.GetAllCategories();
                pizzaDaModificare.CreateIngredients();
                return View("UpdatePizza", pizzaDaModificare);
            }

            var modified = PizzaManager.UpdatePizza(id, pizzaDaModificare.Pizza, pizzaDaModificare.SelectedIngredients);
            if (modified)
            {
                // Richiamiamo la action Index affinché vengano mostrate tutte le pizze
                return RedirectToAction("Index");
            }
            else
                return NotFound();

            /*
            var state = PizzaManager.UpdatePizzaWithEnum(id, pizzaDaModificare);
            switch (state)
            {
                case ResultType.OK:
                    return RedirectToAction("Index");
                    break;
                case ResultType.NotFound:
                    return NotFound();
                    break;
                case ResultType.Exception:
                    return NotFound();
                    break;
            }
            */
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult DeletePizza(int id)
        {
            var deleted = PizzaManager.DeletePizza(id);
            if (deleted)
            {
                // Richiamiamo la action Index affinché vengano mostrate tutte le pizze
                return RedirectToAction("Index");
            }
            else
                return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

la-mia-pizzeria-static/Views/Pizza/GetAllPizzas.cshtml
@model List<Pizza>
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center mt-5"><strong>Lista Pizze</strong></h1>
<div class="card my-5">
    <div class="card-header d-flex justify-content-between align-items-center">
        <div>
            @if (User.IsInRole("ADMIN"))
            {
                <a href="@Url.Action("Create", "Pizza")" class="btn btn-primary">+ Crea nuova pizza</a>
            }
        </div>
        <div>
            <form asp-action="Search" method="post" class="d-flex">
                <input onkeyup="searchPizza()" id="searchInput" type="text" name="searchString" class="form-control" placeholder="Cerca pizza..." />
                <button type="submit" class="btn btn-primary ms-2">Cerca</button>
            </form>
        </div>
    </div>
    <div class="card-body">
        @if (Model == null || !Model.Any())
        {
            <div class="alert alert-warning text-center" role="alert">
                @if (!string.IsNullOrEmpty(ViewData["SearchMessage"] as string))
                {
                    <span>@ViewData["SearchMessage"]</span>
                }
                else
                {
                    <span>Non ci sono pizze disponibili.</span>
                }
            </div>
        }
        else
        {
            <table class="table table-striped table-hover" id="pizzaTable">
                <thead>
                    <tr>
                        <th>
                            Nome
                            <button onclick="toggleSortOrder(0)" class="btn btn-sm btn-light">▲▼</button>
                        </th>
                        @* <th>Categoria</th> *@
                        <th>Descrizione</th>
                        <th style="width: 100px;">Prezzo</th>
                        <th style="width: 100px;">Azioni</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var pizza in Model)
                    {
                        <tr style="cursor: pointer;">
                            <td>@pizza.Name</td>
                            @* <td>@(pizza.Category?.Name ?? "Nessuna categoria")</td> *@
                            <td style="max-width: 300px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                                @pizza.Description
                            </td>
                            <td>@pizza.Price.ToString("F2") €</td>
                            <td class="actions-column">
                                <div class="d-flex justify-content-evenly align-items-center">
                                    <a href="@Url.Action("GetPizza", "Pizza", new { id = pizza.Id })" class="text-primary mx-1"><i class="fa-regular fa-eye"></i></a>
                                    @if (User.IsInRole("ADMIN"))
                                    {
                                        <a href="@Url.Action("Edit", "Pizza", new { id = pizza.Id })" class="text-warning mx-1"><i class="fa-regular fa-pen-to-square"></i></a>
                                        <a onclick="showDeleteModal('@Url.Action("Delete", "Pizza", new { id = pizza.Id })', '@pizza.Name')" class="text-danger mx-1"><i class="fa-solid fa-trash-can"></i></a>
                                    }
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>
@if (TempData["SuccessMessage"] != null)
{
    <div id="successAlert" class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button id="closeAlertButton" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<!-- Include delete modal -->
@Html.Partial("_deleteModal")

<!-- Include pizzaScript.js file -->
<script src="~/js/pizzaScript.js"></script>

la-mia-pizzeria-static/Views/Pizza/GetPizza.cshtml
@model Pizza

@{
    ViewData["Title"] = "Dettagli Pizza";
}

<style>
    .card {
        min-width: 1000px;
    }
</style>

<h1 class="text-center my-5"><strong>Dettagli Pizza</strong></h1>
<div class="row">
        <div class="col-auto mx-auto">
            <!-- Aggiunto mx-auto per centrare la colonna -->
            <div class="card" style="height: 600px; border: 2px solid black; overflow: hidden; border-radius: 10px;">
                @if (Model != null)
                {
                <img src="@Url.Content(Model.ImagePath)" class="card-img-top" alt="Foto Pizza" style="height: 100%; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title"><strong>@Model.Name</strong></h5>
                        <h6 class="card-title">
                            <strong>Categoria:</strong>
                            @Model.Category?.Name
                        </h6>
                        <h6 class="card-text">
                            <strong>Ingredienti:</strong>
                            @if (Model.Ingredients != null && Model.Ingredients.Any())
                            {
                                @* <span class="card-text">
                                    @string.Join(", ", Model.Ingredients
                                             .Select(pi => pi.Ingredient.Name))
                                </span> *@
                            }
                            else
                            {
                                <span>Nessun ingredienti disponibile.</span>
                            }
                        </h6>
                        <h6 class="card-title"><strong>Descrizione:</strong> @Model.Description</h6>
                    </div>
                    <div class="card-footer p-3 border-top-0 text-end" style="background-color: #FFFFFF;">
                        <h5 class="card-text">Prezzo: <strong>@Model.Price €</strong></h5>
                    </div>
                }
                else
                {
                    <p>Unable to retrieve pizza details.</p>
                }
            </div>
            <div class="text-end my-3">
                <a asp-action="Index" class="btn btn-secondary">Torna Indietro</a>
            </div>
        </div>
</div>

la-mia-pizzeria-static/Views/Pizza/Index.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager



<div class="jumbotron text-center mt-5">
    @if (!SignInManager.IsSignedIn(User))
    {
        <h1 class="display-4">Benvenuti alla Pizzeria!</h1>
        <p class="lead">Il posto migliore per trovare e gustare le migliori pizze.</p>
        <hr class="my-4">
        <p>Accedi per gestire le tue pizze o esplorare il nostro menu.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
            <a class="btn btn-secondary btn-lg" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </p>
    }
    else
    {
        <h1>Ciao @UserManager.GetUserName(User)!</h1>
        <h2 class="display-4">Benvenuto/a alla Pizzeria!</h2>
        <p class="lead">Il posto migliore per trovare e gustare le migliori pizze.</p>
    }

la-mia-pizzeria-static/Views/Pizza/PizzaForm.cshtml
@model la_mia_pizzeria_static.Models.Pizza

@{
    bool isEditMode = Model != null && Model.Id != 0;
    ViewData["Title"] = isEditMode ? "Modifica Pizza" : "Crea Pizza";
}

<h1 class="text-center mt-5"><strong>@ViewData["Title"]</strong></h1>

<div class="card p-3 my-5">
    <form asp-controller="Pizza" asp-action="@(isEditMode ? "Edit" : "Create")" method="post" enctype="multipart/form-data" class="row g-3">
        <div class="form-group col-md-6">
            <label asp-for="Name">Nome pizza:</label>
            <input asp-for="Name" class="form-control mt-2 @(ViewData.ModelState["Name"]?.Errors.Count > 0 ? "is-invalid" : "")" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Price">Prezzo:</label>
            <input asp-for="Price" class="form-control mt-2 @(ViewData.ModelState["Price"]?.Errors.Count > 0 ? "is-invalid" : "")" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="ImagePath">Immagine:</label>
            <input asp-for="ImagePath" class="form-control mt-2 @(ViewData.ModelState["ImagePath"]?.Errors.Count > 0 ? "is-invalid" : "")" />
            <span asp-validation-for="ImagePath" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="CategoryId">Categoria:</label>
            <select asp-for="CategoryId" class="form-control mt-2 @(ViewData.ModelState["CategoryId"]?.Errors.Count > 0 ? "is-invalid" : "")" asp-items="ViewBag.Categories"></select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>
        <div class="form-group col-md-12">
            <label asp-for="Description">Descrizione:</label>
            <textarea asp-for="Description" class="form-control mt-2 @(ViewData.ModelState["Description"]?.Errors.Count > 0 ? "is-invalid" : "")"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group col-md-12">
            <label>Ingredienti:</label>
            <div class="row mt-2">
                @if (ViewBag.Ingredients != null)
                {
                    var ingredients = ViewBag.Ingredients as List<Ingredient>;
                    int columns = 4;
                    int itemsPerColumn = (int)Math.Ceiling((double)ingredients.Count / columns);
                    for (int i = 0; i < columns; i++)
                    {
                        <div class="col-md-3">
                            @foreach (var ingredient in ingredients.Skip(i * itemsPerColumn).Take(itemsPerColumn))
                            {
                                <div class="form-check form-switch">
                                    @* <input type="checkbox" role="switch" class="form-check-input" name="selectedIngredients" value="@ingredient.Id"
                                    @(Model.Ingredients != null && Model.Ingredients.Any(pi => pi.Ingredients.Id == ingredient.Id) ? "checked" : "") /> *@
                                    <label class="form-check-label">@ingredient.Name</label>
                                </div>
                            }
                        </div>
                    }
                }
                else
                {
                    <p>Nessun ingrediente disponibile</p>
                }
            </div>
        </div>

        <div class="col-12 d-flex justify-content-end mt-5">
            <button type="submit" class="btn btn-primary mx-1">Salva</button>
            <a asp-action="Index" class="btn btn-secondary mx-1">Torna Indietro</a>
        </div>
    </form>
</div>

la-mia-pizzeria-static/Views/Pizza/_deleteModal.cshtml
<!-- Views/Shared/deleteModal.html -->

<div class="modal fade text-black" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="border-bottom: none;">
                <h5 class="modal-title" id="deleteModalLabel">Conferma Eliminazione</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Sei sicuro di voler cancellare la pizza <span id="pizzaNameToDelete"></span>?
            </div>
            <div class="modal-footer" style="border-top: none;">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                <a id="confirmDeleteButton" href="#" class="btn btn-danger">Elimina</a>
            </div>
        </div>
    </div>
</div>